### ISSUE TITLE
Where WorkshopManagement database is created

### ISSUE THREAD

**Issue by CodeWithKashif** [EdwinVW/pitstop#118]
Hi

I have one quick question that I can see where **WorkshopManagementEventStore** databse is being created **but i am unable to locate where WorkshopManagement db is being created**

`
    // create database
    string sql = "IF NOT EXISTS(SELECT * FROM master.sys.databases WHERE name='WorkshopManagementEventStore') CREATE DATABASE WorkshopManagementEventStore;";
    conn.Execute(sql);
`

**Comment by EdwinVW** [comment]
Hi @CodeWithKashif. 

This database is created by the `WorkshopManagementEventHandler`. This is the service that fills the readmodels in this database by ingesting events from the message broker.
