### ISSUE TITLE
Wrong handling of RabbitMQ messages

### ISSUE THREAD

**Issue by dmitriifilonenko** [EdwinVW/pitstop#17]
Hi Edwin!

Thanks a lot for the great work! Your solution is extreamly helpfull, basically for me it works as a textbook since I'm quite new in microservices development.

While implementing an integration with RabbitMQ I encountered a weird behavior when at some point messages started to pile up at RabbitMQ server without acknowledgement from a consumer. And on a consumer side I faced multiple DbUpdateConcurrencyException's.
It appears that since Consumer_Received method in RabbitMQMessageHandler class works actually asynchronously
```
if (await HandleEvent(ea))
{
...
}
```
then instead of simple EventingBasicConsumer an AsyncEventingBasicConsumer should be used.
You can find more details here: http://gigi.nullneuron.net/gigilabs/the-dangers-of-async-void-event-handlers/

Unfortunately I can't push my branch to this repo in order to create a pull request (due to 403).
So an updated file is attached to this post (I changed an extension to .txt, otherwise GitHub doesn't accept it).

Regards,
Dmitry

[RabbitMQMessageHandler.txt](https://github.com/EdwinVW/pitstop/files/2576094/RabbitMQMessageHandler.txt)

**Comment by EdwinVW** [comment]
Thanks for your interest in my sample solution!

I will look into this. I haven't heard anyone having this issue before, so I will try to reproduce it with the latest version of the RabbitMQ Docker image.

**Comment by EdwinVW** [comment]
@dmitriifilonenko I've updated the messagehandler class based on your version. 

I've also split the infrastructure package into 2 separate packages (Messaging and Service Discovery) and updated all NuGet references in all projects. Make sure to update the dotnet docker images to the latest version and rebuild all docker images (updated to dotnet core 2.1.6).

Thanks again for finding this and creating an issue!

**Comment by EdwinVW** [comment]
About not being able to do a PR: you're not a contributor on this repo so you're not able to push changes directly to it. So if you want to do a pull request, make sure you fork the repo first to your own Github account and clone it on your machine. Apply your changes and push them to the forked repo. You then will be able to create a pull request on the original Pitstop repo.

**Comment by dmitriifilonenko** [comment]
Thank you Edwin!
