### ISSUE TITLE
Error while deploying pitstop on Kubernetes.

### ISSUE THREAD

**Issue by Simonacb** [EdwinVW/pitstop#172]
I meet a error when I'm trying to deploy pitstop in my kubernetes cluster, and the pods status is CrashLoopBackOff.
I run the command 

`kubectl logs <pod_name>` 

and get the output 

`exec /usr/bin/dotnet: exec format error`.

My host platform is x86_64. How can I fix the problem? thanks!

**Comment by EdwinVW** [comment]
Hi @Simonacb. Thanks for your interest in this sample app.

How did you deploy the application? You can use the scripts in the K8S cluster to deploy the app in Kubernetes (see [the docs](https://github.com/EdwinVW/pitstop/wiki/Run%20the%20application%20on%20Kubernetes)).  Also make sure you have built all the docker images in the correct way (see [the docs](https://github.com/EdwinVW/pitstop/wiki/Building%20the%20Docker%20images)). 

I hope this helps!

**Comment by Simonacb** [comment]
Hi @EdwinVW, thank you for your response. I am using the script **start-all.sh** to deploy the app, but my host OS is Linux. Is this app intended only for Windows?

**Comment by EdwinVW** [comment]
No, the solution should work on Windows, MacOS and Linux (it's all .NET 8). I'm running it on MacOS.

Do you see any errors when building the Docker images?

**Comment by Simonacb** [comment]
Thank you @EdwinVW. After rebuilding the images, it was successful. 
Have a good day!
