### ISSUE TITLE
Rebuild script images throws an error 

### ISSUE THREAD

**Issue by oshalabi** [EdwinVW/pitstop#175]
@EdwinVW 

When i run the RebuildAllDockerImages.ps1 script in pitstop I get an error in all the services 

ERROR [***** internal] load metadata for docker.io/library/pitstop-dotnet-sdk-base:1.0  
CANCELED [****** internal] load metadata for docker.io/library/pitstop-dotnet-runtime-base:1.0                                                                              1.0s
Docker tries to pull this image from docker hub even when it's locally exist do you have any suggestions or a fix for this 

Thanks

**Comment by EdwinVW** [comment]
Hi @oshalabi. Thanks for your interest in this sample app!

The `RebuildDockerImages.ps1` script builds Pitstop specific versions of the standard .NET base images. This is to include the `Directory.Packages.props` file in the image. Once these are created, they should not be downloaded from the Docker hub.

Can check check whether the Pitstop specific versions of the base images are present on your machine? Also, can you run the `RebuildDockerImages.ps1` script again, and check whether any errors occur when building the base images?

I haven't been able to reproduce the issue. Do you run Docker desktop or another Docker tool?

**Comment by oshalabi** [comment]
Hi @EdwinVW Thanks for your response 

on my machine i have:
Docker Desktop 4.34.3 (170107) is currently the newest version available.

![Screenshot 2024-10-17 100108](https://github.com/user-attachments/assets/875b6920-552b-4b99-9cc5-92fcea27e47e)

When i run the script in the src folder using the terminal or Powershell 

```bash
./RebuildAllDockerImages.ps1
```

I get this error 

![Screenshot 2024-10-17 100705](https://github.com/user-attachments/assets/577ddc7d-ce3b-4c10-b075-42ca59224d1d)

**Comment by EdwinVW** [comment]
I can see the errors you already mentioned. But I want to see the beginning of this logging, where the Pitstop base images are being built. I want to see if any errors occur there. This could be the reason the images are not present.

**Comment by oshalabi** [comment]
There is no errors while building the Pitstop base images. I made 3 screenshots from the beginning to the point where the error get thrown

![1](https://github.com/user-attachments/assets/c0045b96-a091-42a8-a9e1-392fa529609c)
![2](https://github.com/user-attachments/assets/38eaffe9-dc69-4d9e-addb-0a9428437551)
![3](https://github.com/user-attachments/assets/fd344314-bdcc-42b3-a14a-c9f379cad30b)

**Comment by EdwinVW** [comment]
Thanks for the screenshots. 

I've compared my output with them and it looks similar (for the base images). So my images are also called `docker.io/library/pitstop-....`. But in the next stages (`docker compose build --force-rm`), the local images are used and not downloaded from the repository.

Why this is not the case in your situation is what we need to figure out.

What machine are you using (Win / Mac / Linux) and what processor architecture (amd64 / arm64)? I've had no issues on Windows and Mac. It could be that the images are built with the wrong processor architecture. 

If you do a `docker image inspect pitstop-dotnet-sdk-base:1.0`, what are the values for `Architecture` and `Os`? For me they are `arm64` and `Linux`. I'm running this on a MacBook Pro M2.
