### ISSUE TITLE
docker-compose up not working on Windows

### ISSUE THREAD

**Issue by hakart80** [EdwinVW/pitstop#18]
When try to run docker compose, got following message
docker-compose up
WARNING: The PitStopAIKey variable is not set. Defaulting to a blank string.
ERROR: Volume sqlserverdata declared as external, but could not be found. Please create the volume manually using `docker volume create --name=sqlserverdata` and try again.

**Comment by koleka** [comment]
Did you try to create the volume manually as stated in the error?

**Comment by hakart80** [comment]
Yes when i creating volumes process starting we need 
docker volume create sqlserverdata
docker volume create rabbitmqdata 
or we need to remove externals
I wonder do we need do that manually on Windows

**Comment by koleka** [comment]
It seems like you need to manually run these commands before referencing the volume from the docker compose.

**Comment by EdwinVW** [comment]
Thanks for your interest in the Pitstop solution!

As @koleka mentioned, you indeed need to create the volumes before you can use them from the docker-compose file. 

You can do this by hand, but they are created for you though when you use the `RebuildAllDockerImages` script (see the last paragraph of the [Building the Docker images](https://github.com/EdwinVW/pitstop#building-the-docker-images) in the README).
