### ISSUE TITLE
Store User details for each database that needs it?

### ISSUE THREAD

**Issue by karlbal** [EdwinVW/pitstop#32]
Just a question. Would it be better if i also create a users table for each service? Ex. I if have to display the users full name, etc?

**Comment by EdwinVW** [comment]
I'm not sure I understand your question completely. 
Do you mean the name of the end-user using the web-app??

**Comment by karlbal** [comment]
Sorry for the confusion. Yes sir, that's why I meant.  Just for any reason, we need the full name other the the user name to be displayed on the web app.

**Comment by EdwinVW** [comment]
Thanks for clearing that up.

I would think you would have a separate Microservice for dealing with users (login / logout / profile / ...) - which is not the case now in Pitstop. This service is the system of record for user-info and holds the full name. If another Microservice needs the full name **AND you don't want this service to be dependent on the user service at runtime**, you could ingest user events in that service and cache the full user-name in its private database. So to answer your original question: yes, in that scenario the service has its own table for user info.

Does that make sense and answer your question??

**Comment by karlbal** [comment]
Yes sir. This answered the question.

Thank you very much!
