### ISSUE TITLE
Is the solution file missing?

### ISSUE THREAD

**Issue by ghstahl** [EdwinVW/pitstop#33]
I am trying to build this using Visual Studio 2019

**Comment by EdwinVW** [comment]
Hi @ghstahl. Yes the .sln file was removed because I only work on Pitstop in VS Code. If you want to work in VS, you can create a new solution and add the projects to it. Sorry for the inconvenience!

**Comment by andrazst** [comment]
Hi, @EdwinVW . Thank you for great demo example of Microservices arhitecture. =)
I've imported all the projects to new solution file in VS2017. Now I would like to debug them via VS2017 so I've added Container-Orchestrator Support for each project (Docker-Compose), but I've realize that original dockerfile(s) and docker-compose.yml is not working anymore out of the box. Is there any chance to provide us modified dockerfiles and docker-compose.yml to be able to debug all services via VS2017. Or maybe is there any other more elegant solution to debug microservices via VS2017?
Thank you for your time and reply.
