### ISSUE TITLE
Any Kubernetes talk?

### ISSUE THREAD

**Issue by endeffects** [EdwinVW/pitstop#34]
Hi Edwin, i saw your dotnext docker talk and like to know if there is something similar where you explain kubernetes too for your pitstop sample?

https://www.youtube.com/watch?v=-AfZxdXa7yc

**Comment by EdwinVW** [comment]
Hi @endeffects. Thanks for your interest in my sample application!

To answer your question: this year I did a talk on DotNext St. Petersburg about implementing a service mesh for Pitstop with K8S and Istio. In this session I explain how K8S works and how I use it to run Pitstop:
https://youtu.be/qWUINCZHs6E

I also described how to run Pitstop on K8S. You can find this in the Wiki: 
https://github.com/EdwinVW/pitstop/wiki/Run%20the%20application%20using%20Kubernetes

All K8S scripts are part of the repo. 

I hope this will help to get you started!

**Comment by endeffects** [comment]
Oh thanks alot. Keep up the great work.
