### ISSUE TITLE
Debugging Microservices via VS2017

### ISSUE THREAD

**Issue by andrazst** [EdwinVW/pitstop#35]
Hi, @EdwinVW . Thank you for great demo example of Microservices arhitecture. =)
I've imported all the projects to new solution file in VS2017. Now I would like to debug them via VS2017 so I've added Container-Orchestrator Support for each project (Docker-Compose), but I've realize that original dockerfile(s) and docker-compose.yml is not working anymore out of the box. Is there any chance to provide us modified dockerfiles and docker-compose.yml to be able to debug all services via VS2017. Or maybe is there any other more elegant solution to debug microservices via VS2017?
Thank you for your time and reply.

**Comment by EdwinVW** [comment]
Hi @andrazst. Thanks! And great that you're learning from my sample app.

About your question: in my experience, the logging emitted to Seq has always been enough for me to troubleshoot any issues. I try to stay away from debugging directly inside the containers (using breakpoints or something like that) as much as possible. Therefore I also have no experience with setting this up in VS. 

One way to debug services is by following these steps:
- Start the Pitstop infrastructure components using: ```docker-compose up sqlserver rabbitmq logserver mailserver```.
- Make sure the ASP.NET Core environment is set to _Development_. You can set the environment in VS or through the _ASPNETCORE_ENVIRONMENT_ environment variable. 
- Start the web-app and the service(s) you want to debug in VS (you can configure multiple startup-projects in VS) using _F5_.

For the _Development_ environment, the services and web-app are configured to use _localhost_ in stead of the container-name for connecting to other services. This is configured in the _appsettings.Development.json_ files. So the services don't run in a container and communicate with each-other using localhost. You can set breakpoints in the services while you use them from the web-app.

I hope this information helps you!

**Comment by andrazst** [comment]
Thank you for fast reply. I should learn to read the documentation more in details =) That's should do it, but I've noticed that when running all services (in VS2017 Debug mode) on infrastructure components only 3 databases are created (attachment) and there is also problem with brokerunreachableexception in RabbitMQ. I'm still missing something? =)
![2019-08-05 08_54_52-localhost, 1434 - Azure Data Studio](https://user-images.githubusercontent.com/25555755/62446398-e5b47e00-b762-11e9-8ae8-efb6b5f84850.png)
![2019-08-05 08_53_01-](https://user-images.githubusercontent.com/25555755/62446402-e8af6e80-b762-11e9-82fa-3d7549ca9221.png)
![2019-08-05 09_06_26-c# - How to switch process in Visual Studio Diagnostic Tools Window_ - Stack Ove](https://user-images.githubusercontent.com/25555755/62446406-eb11c880-b762-11e9-9a8c-28136fea83bd.png)

**Comment by reach2deep** [comment]
Hi @andrazst ,Great , even am trying to setup and debug with VS 2017 Community edition, Have some troubles to run with containers, Is it possible to share your VS solution file or can you fork your test sample. it might help me too., Thanks !

**Comment by EdwinVW** [comment]
@andrazst are all the infra services completely finished starting up (check logging) when you start the services? All access to the DB and RabbitMQ is made resilient with automatic retries using Polly. In the logging of the services you can see _"Error connecting to ..., retrying in x seconds"_. But when running in debug mode in VS, maybe you're breaking into the debugger when the exception occurs. 

Also, please check whether all services run in the _Development_ environment?

If I can find the time (on holiday at the moment, also the reason for my delayed reply), I will try to reproduce your situation and see whether I can find the problem.

**Comment by andrazst** [comment]
Sorry for late reply. Yep, all infrastructure services are up and running and all services run in Development environment. Issue is easy to reproduce. No problem, nice holidays =)

**Comment by EdwinVW** [comment]
Try pulling in the latest version of the master branch. I've changed the environment-variable prefix from "DOTNET" to "PITSTOP". This is also used in the _launchSettings.json_ file. Set a global _PITSTOP_ENVIRONMENT_ variable to _Development_ to make sure all console apps run in dev mode.

**Comment by EdwinVW** [comment]
Hi @andrazst. Did you manage to pull the latest version and test whether or not it works now? Thanks!

**Comment by andrazst** [comment]
Hi @EdwinVW. Yes it works fine now. Thank you for the update! =)
