### ISSUE TITLE
Service communication and database

### ISSUE THREAD

**Issue by jbonnett92** [EdwinVW/pitstop#40]
Hi,
I am a bit confused, I can't see any service communication for shared data.
It looks like it is copying data to the services database, wouldn't this cause issues with keeping data up to date?

E.g. many services have a table for "Customer" meaning that them databases have information copied from another database.

Wouldn't it be better to generate a messaging event to a "customer service" and then store the ID in the service that is using that customers information?

Please let me know if I have got anything wrong here.

**Comment by EdwinVW** [comment]
Hi @jbonnett92. Thanks for your interest in this project!

The data is being kept up-to-date using events. If you add a customer for instance, a _CustomerRegistered_ event is published by the _CustomerManagementAPI_ to the message-broker (RabbitMQ). This event is picked up by all the services that need customer info and persisted in their local database (in a form that fits the service). This event-driven approach makes the services autonomous. The _Invoice_ service for instance, can do its work and send invoices, even when the _CustomerManagementAPI_ if offline (for maintenance or an issue).

So yes data is shared between the services. But the _CustomerManagementAPI_ will always be the system-of-record for customer information. All other services have a read-only "cache" of the data locally. And they store the least amount of fields as possible for them to do their work. This is done to reduce the chance of a change to the customer data-structure having an impact on the local cache. The data will only be created and updated by ingesting events.

Does this answer your question?

**Comment by jbonnett92** [comment]
So this is for redundancy? Does it break the rules of normalisation? Not sure how normalisation applies to multiple databases.

**Comment by EdwinVW** [comment]
Not sure I fully understand your question. I used this approach to make every service fully autonomous. Every service owns its own database and normalization is used within this database.

**Comment by EdwinVW** [comment]
Hi @jbonnett92. Did this answer your question?

**Comment by jbonnett92** [comment]
Sorry about the late reply, I was on training. Yes that answered the question.

**Comment by jbonnett92** [comment]
Do you by chance have any tutorials on implementing the concepts that you've used in this project?
I am new to .NET Core (Though I have been developing Umbraco for the last two years for my job, which is .NET Framework) and I have basic knowledge how microservices work and what not to do. I just can't seem to know where to start implementing.

**Comment by EdwinVW** [comment]
No problem @jbonnett92. Thanks for the update.

For me it has been a journey (so no overnight thing). I have learned all the concepts I've put into Pitstop primarily by reading books. These are a couple I can recommend:

- [Building Microservices by Sam Newman](https://www.amazon.com/Building-Microservices-Designing-Fine-Grained-Systems/dp/1491950358)
- [Exploring CQRS and Event Sourcing](https://www.microsoft.com/en-us/download/details.aspx?id=34774). This is an older book, but I've really learned CQRS and the event-driven approach from this book. Samples are not .NET Core but it's more about the concepts.
- [Patterns, Principles, and Practices of Domain-Driven Design](https://www.amazon.com/Patterns-Principles-Practices-Domain-Driven-Design/dp/1118714709).

I also had the privilege of following a course by Greg Young about CQRS and Event Sourcing in London. That was also an eye-opener for me.

And finally it's been a lot of sparring with fellow software architects about - and experimenting with - the concepts I've picked up from the books and how to implement them. This is why Pitstop exists. It's my go to project for trying new concepts and technology (I'm currently thinking about porting the front-end to Blazor for instance). 

I've done some talks on how I've built Pitstop using .NET Core and docker. This will also go into some of the architectural concepts. Maybe this recording will help: [Building microservices with .NET Core and docker](https://www.youtube.com/watch?v=-AfZxdXa7yc).

I hope this will get you started.

**Comment by jbonnett92** [comment]
Thank you,
I also noticed that in [WorkshopManagementAPI](https://github.com/EdwinVW/pitstop/blob/master/src/WorkshopManagementAPI/Repositories/SqlServerRefDataRepository.cs) repo's you reference databases from other microservices.

Shouldn't you query the service that the database is paired with? Like in this illustration? 

![](https://trungtq.com/wp-content/uploads/2018/12/1_BtrrWwFy86mGaXANbjz9AQ.png)

**Comment by EdwinVW** [comment]
Yes @jbonnett92, that's how it should be done. 

A microservice is a concept and the WorkshopManagement microservice contains 2 components: an API for handling commands (_WorkshopManagementAPI_) and an eventhandler for ingesting events from other services (_WorkshopManagementEventHandler_). Both components are part of the implementation of the WorkshopManagement microservice. And hence, both databases are only used within this microservice. This is also how I visualized it in the solution architecture diagram:

<img src="https://github.com/EdwinVW/pitstop/wiki/img/solution-architecture.png" />

**Comment by jbonnett92** [comment]
Please can you add a authentication service? It would be an interesting one to see.

**Comment by EdwinVW** [comment]
This is why I use an message broker. The messages will be kept in the queue while the service is down. When the service is started, it will just resume picking up the next message from the queue.

It's on my backlog.

**Comment by jbonnett92** [comment]
This may be a problem when you scale up the services, lets say that we create multiple invoice service instances, we publish and even that the invoice service consumes, that means that only one instance can consume using the broker (which in some case is ok, means that it is not doing the same thing twice) though this hurts throughput, even if we manage to get the multiple instances consuming the event, would there be database locking? What would you suggest to this? 

My thinking is that RabbitMQ can handle 50k messages in a single queue and if we (for some reason) need more, what route do we take then? It just doesn't seem as scalable as microservices intend to be. I know that RabbitMQ can shard queues, though that also hurts throughput.

**Comment by EdwinVW** [comment]
RabbitMQ handles competing consumers on the queue. So if you would run multiple instances of the invoice service, each instance of the service will get a different message and the load will be balanced that way. This is also a reason to choose for a more sophisticated message-broker. 

Database locking could be a problem, but using a retry mechanism (which RabbitMQ offers out of the box) with optimistic concurrency control would be enough here. 

If you need very high throughput (way more that necessary for the Pitstop scenario), you should look at a different architecture and use concepts like streaming. Like I said, microservices is a concept that can be implemented in several ways. I've used the setup I've used for Pitstop also for production applications that could handle pretty large workloads. So it depends ;)
