### ISSUE TITLE
Event sourcing/storing with SAGA

### ISSUE THREAD

**Issue by findkashif** [EdwinVW/pitstop#43]
_(please correct me if i am wrong or something is missing)_

Event sourcing helps in storing all the changes (events) to the system, rather than just its current/latest  state, means we can persist different version(change history) for for any domain object.
So we can see the audit trail and or back track(roll back) to an early stage.

****Questions:**
(a)**
So in future do you have any plan to use SAGA to demonstrate the roll back among multiple micro-services?

**(b)**
Kindly also explain the realtime usage of IsReplaying property
```
    public class WorkshopPlanning
    {
        /// <summary>
        /// Indication whether the aggregate is replaying events (true) or not (false).
        /// </summary>
        private bool IsReplaying { get; set; } = false;

```

and of course thanks again for your wonderful help and support - I am highly obliged and grateful to you!

_Originally posted by @findkashif in https://github.com/EdwinVW/pitstop/issues/42#issuecomment-538516625_

**Comment by EdwinVW** [comment]
**(a)**
I'm not sure I get your saga question. I know sagas as a way to orchestrate a process that spans multiple microservices. I would not use the eventstore to do rollbacks. Only "roll-forwards". If you need to fix anything in an event-sourced service, you add events to correct things (like an accountants ledger). Such a correction could be part of a saga (as a compensating action).

**(b)**
The _IsReplaying_ indication is set when we are replaying events from the event-store to rebuild the state of the aggregate (using the set of events received from the database and passed to the constructor). This offers us the opportunity to change behavior in the event-handlers when replaying. I have not used this in Pitstop, but this is standard pattern I always use. I have used it once in a different situation to disable logging of event-handling during replay. 

Again, I hope I've answered your questions  :)

**Comment by findkashif** [comment]
Thanks again for detailed answer

The Saga Pattern is as microservices architectural pattern to implement a transaction that spans multiple services.

https://dzone.com/articles/microservices-using-saga-pattern

So basically this pitstop project really great place where you have implemented most of the aspect of DDD with a very pragmatic approach.

So i was looking for, whether you have any future plan to demonstrate enabling Transaction among multiple microservices.

**Comment by EdwinVW** [comment]
What kind of transactions would you like to see? I guess (and hope) you're not referring to ACID transactions over services (this is usually a very bad (expensive) idea). 

I always use the eventual consistency model over services using events. I have no compensating actions in Pitstop, but this is perfectly doable with the current setup. A service could emit an event that would trigger a compensating action in another service. 

But I always strive to keep transactions within the boundaries of a service. If this is not possible and you need multi-service transactions, you should look at your service boundaries. Perhaps the services shouldn't have been split then (DDD bounded contexts).

**Comment by findkashif** [comment]
Yes I was  not talking for ACID transaction and i was referring something like
https://dzone.com/articles/distributed-sagas-for-microservices
Here it has given very common and famous example of flight, car and hotel booking example.
and mentioned clearly:
_"With the microservices approach, you can’t just book a flight, a car, and a hotel in a single ACID transaction. To do it consistently, you would be required to create a distributed transaction."_

....and yes I also see/agree it is doable with current architecture setup with Pitstop, just wanted to check with you whether do you have any future plan to find-out & implement any such example for demonstration purpose.

**Comment by EdwinVW** [comment]
Yes, those are the canonical examples. But no, I have no plans to add something like that to Pitstop.
