### ISSUE TITLE
Solution needs security

### ISSUE THREAD

**Issue by EdwinVW** [EdwinVW/pitstop#6]
Add security based on OAUTH2/OpenIDConnect to the solution. Let's use IdentityServer to implement this.

**Comment by juliuskrah** [comment]
Are you already workin on this or can I take a pass at it?

**Comment by EdwinVW** [comment]
@juliuskrah, thanks for your offer to contribute! 

I had already started working on this and had basic stuff up and running. But I'm a bit hesitant to finish and release it. Mainly because the application must stay small and simple enough for me to use it for demo's and it already has lots of moving parts. So I've decided to not add more complexity and was about to close this issue.
