### ISSUE TITLE
Future plan

### ISSUE THREAD

**Issue by Urgen-Dorjee** [EdwinVW/pitstop#66]
I am wondering, if you could make those services which run on the background like time, invoice, notification, workshopmanagementeventhandler and audit into gRPC in future that would be more interesting!

Thanks,

**Comment by EdwinVW** [comment]
Hi @Urgen-Dorjee. Thank for this suggestion. But these services are background-workers and are supposed to be triggered only by events published to the message broker. They are not meant to be called directly. So I don't think implementing gRPC for these services would be beneficial. 

All the API services (like the _CustomerManagementAPI_) could be fitted with gRPC to replace the ASP.NET Core WebAPI. I have done some experimenting with that and it works fine, but I see no advantage to change the communication framework to gRPC at this point in time. But feel free to experiment with this yourself!
