### ISSUE TITLE
Do we really need multiple retries policy setup?

### ISSUE THREAD

**Issue by Urgen-Dorjee** [EdwinVW/pitstop#70]
I am just curious, do we really need multiple retry policies setup for initializing a database?

https://github.com/EdwinVW/pitstop/blob/99d2ef6a180e3e9dfc7ddd259532cc4ff7dbf72c/src/WorkshopManagementEventHandler/Program.cs#L59

https://github.com/EdwinVW/pitstop/blob/99d2ef6a180e3e9dfc7ddd259532cc4ff7dbf72c/src/WorkshopManagementEventHandler/DataAccess/DBInitializer.cs#L14

Is it not a redundant line of code? Is there any significant to have same policy in two different places. 

Thanks

**Comment by EdwinVW** [comment]
Yes, this seems redundant. I'll look into it. Thanks!

**Comment by EdwinVW** [comment]
Fixed this in d5afbc34735abcc706a6ca7f8f0ea7fb13a0ccee.
