### ISSUE TITLE
Parameter-less constructor

### ISSUE THREAD

**Issue by Urgen-Dorjee** [EdwinVW/pitstop#71]
Why would EF Core requires this parameter-less constructor for generating a migration schema?

https://github.com/EdwinVW/pitstop/blob/99d2ef6a180e3e9dfc7ddd259532cc4ff7dbf72c/src/WorkshopManagementEventHandler/DataAccess/WorkshopManagementDBContext.cs#L8

Thanks,

**Comment by EdwinVW** [comment]
I believe this is necessary for using the `dotnet ef` command-line tooling to migrate the database manually. But I'm not sure (I implemented this a long time ago). Maybe this is not necessary anymore with the latest version of EF Core. I'll look into it.

**Comment by EdwinVW** [comment]
I haven't been able to look into this (other priorities). Sorry.
