### ISSUE TITLE
How do I

### ISSUE THREAD

**Issue by gurelsoycaner** [EdwinVW/pitstop#76]
Hi,

In an event-driven autonomous microservice environment, how do I push data previously-stored in a database table "COMPANY" through RabbitMQ to a newly subscribed or created service with Database PRODUCT that has a copy of table "COMPANY" from COMPANY-Database?

Thanks in advance.

**Comment by EdwinVW** [comment]
I don't understand your question. I also fail to see any relationship with the Pitstop context. 
Could you please elaborate on the question a bit more?

**Comment by gurelsoycaner** [comment]
> I don't understand your question. I also fail to see any relationship with the Pitstop context.
> Could you please elaborate on the question a bit more?

Yes, sir, you're very right, it has nothing to do with Pitshop context.

I was seeking for your advice on how to, in an EVENT-Sourcing ANONYMOUS microservice environment 
push OLD (by old I mean already created) customer data from customer-table in "CUSTOMER" database to customer table in "INVIOCING" database through RABBITMQ?

Not: Invoice service was newly created and I need to get all active customer data from CUSTOMER database to INVIOCING database.

**Comment by EdwinVW** [comment]
Ah, I see. Thanks for clearing that up.

I personally would not use RabbitMQ for such a task. Assuming it's a one-time synchronization of the tables between two separate databases, I would use a more ETL (Extract, Transform, Load) like approach. So get the data from the source table in bulk and then bulk-insert it into the target table. If the source and target schema is not similar, you could do some kind of transformation of the data before inserting it.

It's pretty easy to build something like that yourself. But there are also several tools available you can use for that (e.g. [SSIS](https://docs.microsoft.com/en-us/sql/integration-services/sql-server-integration-services?view=sqlallproducts-allversions)).

If - after this initial one-time migration - you need to keep the tables in sync, then I would publish the individual events from the source service to the target service and store them there.

I hope this helps.

**Comment by gurelsoycaner** [comment]
> I don't understand your question. I also fail to see any relationship with the Pitstop context.
> Could you please elaborate on the question a bit more?


Thank you very much. I was thinking of persisting the data in RabbiMq to local storage and then try pull data from there.
