### ISSUE TITLE
Wiki mentions running Kubernetes dashboard, but it seems to have moved

### ISSUE THREAD

**Issue by bartvanderwal** [EdwinVW/pitstop#86]
Hi @EdwinVW,

Finally got around to checking your pitstop app, after your talk on service mesh/istio

On [this page on your wiki](https://github.com/EdwinVW/pitstop/wiki/Run-the-application-using-Kubernetes#kubernetes-dashboard) you mention using Kubernetes dashboard. But the command given causes an error:
`unable to read URL`

It seems the `.yaml` and everything seems to have moved within githubusercontent.com from:

```console
https://raw.githubusercontent.com/kubernetes/dashboard/master/aio/deploy/recommended/kubernetes-dashboard.yaml\
```
to below url as given in the command in the README.md of https://github.com/kubernetes/dashboard: 

```console
kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.2.0/aio/deploy/recommended.yaml
```

**Comment by EdwinVW** [comment]
Thanks for the heads-up @bartvanderwal. I've fixed it.
