### ISSUE TITLE
Issue with microsoft/mssql-server-linux:latest 

### ISSUE THREAD

**Issue by findkashif** [EdwinVW/pitstop#92]
docker-compose  is not working for me today.
I tried several times and getting same error again and again as it is unable to pull **microsoft/mssql-server-linux:latest**
I tried it on other machine too.

`docker-compose up -d`

`Pulling sqlserver (microsoft/mssql-server-linux:latest)...
ERROR: manifest for microsoft/mssql-server-linux:latest not found: manifest unknown: manifest unknown`

**Comment by EdwinVW** [comment]
Hi @findkashif 

Thanks for finding and registering this issue. Microsoft has moved their Docker images to a different registry (mcr.microsoft.com). So the the image for SQL Server on Linux should be changed.

I fixed this in commit e689b4c1e1dbbfc1f863ef50d9167630156f54e6. Please pull the latest version of the repo and try again.

**Comment by findkashif** [comment]
Thanks a lot for your quick response and fix. Yes it is working fine now!

I have following questions here and I want to learn it from your experience:

1. This is a bit common issue I have had seen with docker images that Microsoft (or any other owner) may change their location/tags etc. so this may cause defect on a live system too.
What is the best way to handle or avoid this with applications running in production.

2. I also suspected this issue that either its tag is changed or it is moved to some other location etc.
However I was unable to find the actual issue and its solution. 
So in future something similar happens then how should I trace and fix this.

3. Also in docker world many times I struggle around what is right base image, which version and tag should i use. I find it bit confusing.

**Comment by EdwinVW** [comment]
1. When images are running in production, their image is already present and it shouldn't be an issue. In your dev/test/acceptance environment, you can tackle this by always building the environment from scratch. Then you find the issue there and can fix it before it goes through to production.

2. Always check out Docker Hub first. As you can see with the SQL Server on Linux images, they can still be found on [Docker Hub](https://hub.docker.com/_/microsoft-mssql-server) but the registry is mcr.microsoft.com.

3. Always check the documentation of the base images. Often, the publisher describes the specific use-cases for different base-images. Sometimes a base image is completely stripped and only contains core functionality to yield a smaller image. But if you need more features, you might need to pick a bigger base image that contains those features. If you look at the .NET base images, some contain the entire .NET SDK (for building the software) and others only contain the .NET runtime for production. In Pitstop I use both base images in what is called a multi-stage Docker build. The actual image that will be used for running the container only contains the .NET runtime and is therefore a lot smaller. So unfortunately, there's no single answer to your question ... it depends.
