### ISSUE TITLE
RabbitMQ Connection approach

### ISSUE THREAD

**Issue by findkashif** [EdwinVW/pitstop#94]
Hi @EdwinVW 

I have a question around Rabbit MQ Connection approach

In this project we are maintaining Host, UserName and Password separately and it is working totally fine as I am able to connect Rabbitmq running in docker or Rabbitmq running locally without docker

**RabbitMQ Connection approaches**
### Approach 1
` var factory = new ConnectionFactory { HostName = _host, UserName = _username, Password = _password}`
`  using (var connection = factory.CreateConnection())`

### Approach 2
`var factory = new ConnectionFactory {Uri = new Uri(_uri)};`
`using (var connection = factory.CreateConnection())`

I see approach 2 is bit more common on internet where they maintain complete uri(_similar to connection string_) like below
`"Uri": "amqp://rabbitmquser:DEBmbwkSrzy9D1T9cJfa@rabbitmq"`

Sir can you please outline the pros and cons for both approaches

**Comment by EdwinVW** [comment]
I always use approach 1. 
I kindly redirect you to the RabbitMQ documentation for any information of pros and cons of each approach.

**Comment by findkashif** [comment]
Hi @EdwinVW 

I have asked this questions because I got a URI like following
`"Uri": "amqps://mzjyytub:mypassword123@puffin.rmq2.cloudamqp.com/mzjyytub"`

Here I am able to connect with complete URI(_Approach 2_) but unable to connect with Approach 1

I tried segregating it like following(_and some other combination too_) but it nothing work for me in approach1

```
"Host": "puffin.rmq2.cloudamqp.com",
"Username": "mzjyytub",
"Password": "mypassword123"
```
