### ISSUE TITLE
Azure SQL is not supported

### ISSUE THREAD

**Issue by rouke-broersma** [EdwinVW/pitstop#95]
See: https://github.com/EdwinVW/pitstop/blob/master/src/NotificationService/Repositories/SqlServerNotificationRepository.cs#L39

DB_ID always returns NULL for azure sql (single database). 

We could instead use 

```sql
"IF NOT EXISTS(SELECT * FROM master.sys.databases WHERE name='Notification') CREATE DATABASE Notification;"
```

The USE command is also not allowed on azure sql single database which is used by ChangeDatabase: https://github.com/EdwinVW/pitstop/blob/master/src/NotificationService/Repositories/SqlServerNotificationRepository.cs#L44

We can replace this with closing the sql connection to master and creating a new sql connection to the target database.

This does work on azure sql. Would this change be acceptable?

**Comment by EdwinVW** [comment]
Yes that's fine - providing it also keeps working on SQL Server (which I assume is the case). 
Will you do a PR (for all applicable services) or do you want me to fix this?

**Comment by EdwinVW** [comment]
Fixed in commit https://github.com/EdwinVW/pitstop/commit/9383def17cb78523c53549c4a69be2599ecbf47c
Successfully these changes tested on SQL Server.

**Comment by EdwinVW** [comment]
Can you check whether this is sufficient to fix the issue?

**Comment by rouke-broersma** [comment]
This is the same change we made to our fork  👍 

The only difference is that we did a `conn.OpenAsync();` in the new connection scope but if you say the change works fine without it on SQL server then I guess it's not neccesary? 🤷

**Comment by EdwinVW** [comment]
Yes, it makes sense to explicitly open the connection. I'll create a fix for that.

**Comment by EdwinVW** [comment]
See commit https://github.com/EdwinVW/pitstop/commit/f243358e7b66e2d341905df7d142f32e1dd0912e

I've also changed the SqlServerWorkshopPlanningEventSourceRepository of the WorkshopManagementAPI so its structure is identical to that of the other two repos.
